### ISSUE TITLE
oauth2 代码中缺少验证scope 密码模式不完整

### ISSUE THREAD

**Issue by jumuning** [shanzhaozhen/best-cloud#3]

**Comment by shanzhaozhen** [comment]
> _No description provided._

在 `OAuth2ResourceOwnerPasswordAuthenticationProvider` 类中有对 `scope ` 进行验证

**Comment by jumuning** [comment]
有验证但是无法验证判断是否和数据库中的一致

**Comment by jumuning** [comment]
好吧，我是代码不是最新的
