### ISSUE TITLE
userinfo endpoint 401

### ISSUE THREAD

**Issue by weijie0** [shanzhaozhen/best-cloud#4]
调用userinfo端点报invalid token

**Comment by shanzhaozhen** [comment]
> 调用userinfo端点报invalid token

请求头需要使用access_token

**Comment by weijie0** [comment]
> > 调用userinfo端点报invalid token
> 
> 请求头需要使用access_token

是的，请求头使用了access_token,但是仍然报invalid token，如果没传的话不会返回任何内容，我打断点跟踪了下，userinfo端点是不是只能在oidc下使用，如果没有id_token,就有这个问题，请教，谢谢

**Comment by shanzhaozhen** [comment]
> > > 调用userinfo端点报invalid token
> > 
> > 
> > 请求头需要使用access_token
> 
> 是的，请求头使用了access_token,但是仍然报invalid token，如果没传的话不会返回任何内容，我打断点跟踪了下，userinfo端点是不是只能在oidc下使用，如果没有id_token,就有这个问题，请教，谢谢

这是肯定的，因为并不是OIDC类型账号就不存在这类型的信息了，所以直接返回错误是正常的

**Comment by weijie0** [comment]
感谢回复，我在使用密码模式登陆时，设置了scope为openid，但是没有返回id_token是怎么回事呢？

**Comment by shanzhaozhen** [comment]
> 



> 感谢回复，我在使用密码模式登陆时，设置了scope为openid，但是没有返回id_token是怎么回事呢？

密码模式就不可能是oidc了，首先认证方式大于scope的范围

**Comment by weijie0** [comment]
> > 感谢回复，我在使用密码模式登陆时，设置了scope为openid，但是没有返回id_token是怎么回事呢？
> 
> 密码模式就不可能是oidc了，首先认证方式大于scope的范围

为什么不行呢，密码模式应该也可以的吧
